version: '3.9'
services:
  nest:
    build: .
    restart: always
    ports:
      - '5000:5000'
      - '9229:9229'
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      NODE_ENV: 'prod'
      TYPE_ORM: 'on'
    command: npm run start:debug

  pg4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'lismgmk2@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-load:/var/lib/pgadmin

volumes:
  pgadmin-load:
