version: '3.9'
services:
  postgres:
    image: postgres:14.6
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '2156128'
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data